#include "TdxPluginHeader.h"
#include "tdx_config.h" // Generated by build_tdx_dll.py
#include <windows.h>
#include <vector>

//=============================================================================
// C++ Core Algorithms (Bi, Seg, ZS, BSP)
//=============================================================================

// 顶底扫描定位函数 (Parse1)
void Parse1(int nCount, float *pOut, float *pHigh, float *pLow) {
    if (nCount <= 0) return;
    for (int i = 0; i < nCount; i++) {
        pOut[i] = 0.0f;
    }

    int nState = -1;
    int nHigh  = 0;
    int nLow   = 0;

    for (int i = 1; i < nCount; i++) {
        if (nState == 1) {
            if (pHigh[i] >= pHigh[nHigh]) {
                pOut[nHigh] = 0.0f;
                nHigh = i;
                pOut[nHigh] = 1.0f;
            }
            if ((pHigh[i] < pHigh[nHigh]) && (pLow[i] < pLow[nHigh])) {
                pOut[nHigh] = 1.0f;
                nState = -1;
                nLow   = i;
                pOut[nLow] = -1.0f;
            }
        }
        else if (nState == -1) {
            if (pLow[i] <= pLow[nLow]) {
                pOut[nLow] = 0.0f;
                nLow = i;
                pOut[nLow] = -1.0f;
            }
            if ((pLow[i] > pLow[nLow]) && (pHigh[i] > pHigh[nLow])) {
                pOut[nLow] = -1.0f;
                nState = 1;
                nHigh  = i;
                pOut[nHigh] = 1.0f;
            }
        }
    }
}

// 化简函数 (至少5根K线完成一笔)
void Parse2(int nCount, float *pOut, float *pHigh, float *pLow) {
    int nCurrTop = 0, nPrevTop = 0;
    int nCurrBot = 0, nPrevBot = 0;

    for (int i = 0; i < nCount; i++) {
        if (pOut[i] == 1.0f) {
            nPrevTop = nCurrTop;
            nCurrTop = i;

            if (nPrevTop > 0 && nCurrBot > 0 && nPrevBot > 0) {
                if ((pHigh[nCurrTop] >= pHigh[nPrevTop]) && (pLow[nCurrBot] > pLow[nPrevBot])) {
                    if (((nCurrTop - nCurrBot < 4) && (nCount - nCurrTop > 4)) ||
                        (nCurrBot - nPrevTop < 4) || (nPrevTop - nPrevBot < 4)) {
                        pOut[nCurrBot] = 0.0f;
                        pOut[nPrevTop] = 0.0f;
                    }
                }
            }
        }
        else if (pOut[i] == -1.0f) {
            nPrevBot = nCurrBot;
            nCurrBot = i;

            if (nCurrBot > 0 && nCurrTop > 0 && nPrevTop > 0 && nPrevBot > 0) {
                if ((pLow[nCurrBot] <= pLow[nPrevBot]) && (pHigh[nCurrTop] < pHigh[nPrevTop])) {
                    if (((nCurrBot - nCurrTop < 4) && (nCount - nCurrBot > 4)) ||
                        (nCurrTop - nPrevBot < 4) || (nPrevBot - nPrevTop < 4)) {
                        pOut[nCurrTop] = 0.0f;
                        pOut[nPrevBot] = 0.0f;
                    }
                }
            }
        }
    }
}

// Func1: 笔标记
void Func1(int nCount, float *pOut, float *pHigh, float *pLow, float *pExt) {
    Parse1(nCount, pOut, pHigh, pLow);
    
    // Check CFG_BI_STRICT or other bi configs implicitly (example)
    int times = 1; // Default parsing times
    for(int k = 0; k < times; k++) {
        Parse2(nCount, pOut, pHigh, pLow);
    }
}

// 通用分析函数：提取段、中枢及买卖点
void CalculateChanElements(int nCount, float* pIn, float* pHigh, float* pLow, float* pOut, int type) {
    if (nCount <= 0) return;
    for (int i = 0; i < nCount; ++i) pOut[i] = 0.0f;

    std::vector<int> points;
    for (int i = 0; i < nCount; ++i) {
        if (pIn[i] == 1.0f || pIn[i] == -1.0f) {
            points.push_back(i);
        }
    }

    if (points.size() < 4) return;

    std::vector<float> zs_h(nCount, 0.0f);
    std::vector<float> zs_l(nCount, 0.0f);
    std::vector<float> zs_flag(nCount, 0.0f);
    std::vector<float> bsp(nCount, 0.0f);
    std::vector<float> seg(nCount, 0.0f);

    int last_zs_end = -1;

    // 更好的段划分 (包含至少3笔的反向突破线段)
    if (points.size() > 0) {
        int last_seg_k = 0; // index in points array
        seg[points[last_seg_k]] = pIn[points[last_seg_k]];
        
        for (size_t k = 1; k < points.size(); ++k) {
            int idx = points[k];
            if (pIn[idx] != pIn[points[last_seg_k]]) {
                // 方向相反，必须间隔至少3笔才能成段（即k - last_seg_k >= 3）
                if (k - last_seg_k >= 3) {
                    seg[idx] = pIn[idx];
                    last_seg_k = k;
                }
            } else {
                // 方向相同，延伸段的极值点
                if (pIn[idx] == 1.0f && pHigh[idx] > pHigh[points[last_seg_k]]) {
                    seg[points[last_seg_k]] = 0.0f; // 清除之前的顶点
                    seg[idx] = 1.0f;                // 标记新的顶点
                    last_seg_k = k;
                } else if (pIn[idx] == -1.0f && pLow[idx] < pLow[points[last_seg_k]]) {
                    seg[points[last_seg_k]] = 0.0f; 
                    seg[idx] = -1.0f;               
                    last_seg_k = k;
                }
            }
        }
    }

    // 中枢计算逻辑 (3笔重叠)
    for (size_t i = 0; i < points.size() - 3; ++i) {
        if ((int)i < last_zs_end) continue;

        int p0 = points[i];
        int p1 = points[i+1];
        int p2 = points[i+2];
        int p3 = points[i+3];

        float v0 = pIn[p0] == 1.0f ? pHigh[p0] : pLow[p0];
        float v1 = pIn[p1] == 1.0f ? pHigh[p1] : pLow[p1];
        float v2 = pIn[p2] == 1.0f ? pHigh[p2] : pLow[p2];
        float v3 = pIn[p3] == 1.0f ? pHigh[p3] : pLow[p3];

        float zg, zd;
        if (pIn[p1] == 1.0f) {
            // p0 是低点
            zg = (v1 < v3) ? v1 : v3; // 顶的相对低点为中枢高ZG
            zd = (v0 > v2) ? v0 : v2; // 底的相对高点为中枢低ZD
        } else {
            // p0 是高点
            zg = (v0 < v2) ? v0 : v2; 
            zd = (v1 > v3) ? v1 : v3; 
        }

        // 验证中枢区间重叠
        if (zd < zg) {
            zs_flag[p0] = 1.0f;
            zs_flag[p3] = 2.0f;
            zs_h[p0] = zg; zs_h[p3] = zg;
            zs_l[p0] = zd; zs_l[p3] = zd;
            last_zs_end = i + 4; // 强制下一个中枢跨越连接段（跳过p3点共享，避免端点Flag与高度数组被覆盖）

            // 粗略买卖点映射：中枢离开段
            if (pIn[p3] == -1.0f) {
                bsp[p3] = 1.0f; // 1买
                if (i + 5 < points.size()) {
                    int p5 = points[i+5];
                    if (pLow[p5] > zg) {
                        bsp[p5] = 3.0f; // 3买
                    } else if (pLow[p5] > pLow[p3]) {
                        bsp[p5] = 2.0f; // 2买
                    }
                }
            } else {
                bsp[p3] = 11.0f; // 1卖
                if (i + 5 < points.size()) {
                    int p5 = points[i+5];
                    if (pHigh[p5] < zd) {
                        bsp[p5] = 13.0f; // 3卖
                    } else if (pHigh[p5] < pHigh[p3]) {
                        bsp[p5] = 12.0f; // 2卖
                    }
                }
            }
        }
    }

    for (int i = 0; i < nCount; ++i) {
        if (type == 2) pOut[i] = zs_h[i];
        else if (type == 3) pOut[i] = zs_l[i];
        else if (type == 4) pOut[i] = zs_flag[i];
        else if (type == 5) pOut[i] = bsp[i];
        else if (type == 6) pOut[i] = seg[i];
    }
}

// Func2 & 3: ZS High/Low Support
void Func2(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    CalculateChanElements(nCount, pIn, pHigh, pLow, pOut, 2);
}

void Func3(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    CalculateChanElements(nCount, pIn, pHigh, pLow, pOut, 3);
}

void Func4(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    CalculateChanElements(nCount, pIn, pHigh, pLow, pOut, 4);
}

void Func5(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    CalculateChanElements(nCount, pIn, pHigh, pLow, pOut, 5);
}

void Func6(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    CalculateChanElements(nCount, pIn, pHigh, pLow, pOut, 6);
}

void Func7(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    if (pIn == NULL || nCount <= 0) {
        if (pOut) for (int i = 0; i < nCount; ++i) pOut[i] = 0.0f;
        return;
    }
    
    float last_state = 0.0f;
    for (int i = 0; i < nCount; ++i) { 
        pOut[i] = 0.0f;
        float current_state = 0.0f;
        
        // 跨周期获取到的通常是持续状态(BI_VAL)
        if (pIn[i] > 0.5f) current_state = 1.0f;
        else if (pIn[i] < -0.5f) current_state = -1.0f;
        
        // 当状态发生跳变时，在本周期标记一个脉冲，用于DRAWLINE连线
        if (current_state != 0.0f && last_state != 0.0f && current_state != last_state) {
            pOut[i] = current_state; 
        }
        
        // 更新前一个状态
        if (current_state != 0.0f) {
            last_state = current_state;
        }
    } 
}

void Func8(int nCount, float *pOut, float *pIn, float *pHigh, float *pLow) {
    for (int i = 0; i < nCount; ++i) { pOut[i] = 0.0f; } // Extra
}

static PluginTCalcFuncInfo Info[] = {
    {1, &Func1},
    {2, &Func2},
    {3, &Func3},
    {4, &Func4},
    {5, &Func5},
    {6, &Func6},
    {7, &Func7},
    {8, &Func8},
    {0, NULL},
};

DECLSPEC_EXPORT BOOL RegisterTdxFunc(PluginTCalcFuncInfo **pInfo) {
    if (*pInfo == NULL) {
        *pInfo = Info;
        return TRUE;
    }
    return FALSE;
}
